### Post a test item to the db
POST http://localhost:8080/
Content-Type: application/json

{
  "name": "Beans"

}

### Get all items
GET http://localhost:8080/

### Delete all items
DELETE http://localhost:8080